image: tmaier/docker-compose:latest
 
stages:
  - build
  - test
  - deploy
  
Build-app:
  stage: build
  script:
    - echo 'Building app'
    
Testing:
  stage: test
  script:
    - docker-compose -f docker-compose.yml up --abort-on-container-exit --exit-code-from lippia
  allow_failure: true
  artifacts:
    paths:
      - target/reports/

Deploy:
  stage: deploy
  script: 
    - echo 'deploying app in custom server'
