# Note: It requires docker-compose 1.13.0
#
# Usage: docker-compose up -d
version: "2.2"

services:

  lippia:
    image: crowdar/lippia:3.2.1.1
    volumes:  
        - /builds/root/lippia-mobile-sample-project/mnt:/mnt
    working_dir: /mnt
    command: pwd && ls -la
